# Generated by Django 2.1.4 on 2018-12-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Reviewed by Manager'), (2, 'Closed')], default=0),
        ),
    ]
